admins: []
forwards:
- source: -1001214634079
  dest:
  - me
  - -595809887
  - -1001543196901
  - -595083081
  offset: 85
  end: 0
show_forwarded_from: true
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
