# this is sample configuration file
# change this to suit your needs
# link to tgcf original repo https://github.com/aahnik/tgcf
# learn how to configure tgcf https://git.io/J3NuZ
# learn how to run on github actions https://git.io/J3NuY
# this is a yaml file, learn about yaml syntax here https://git.io/J3NuL
# MIT LICENSE
# AAHNIK 2021

########################################

forwards:
  - source: "-1001214634079"
    dest: [me, "-595809887", "-1001543196901", "-595083081"]
    offset: 0
  # - source: -1001
  #   dest: []
  #   offset: 0
  # add more sources if you wish

past:
  delay: 3 # wait for 3s after forwarding each message

plugins:
  # specify the plugins you want to use
  filter:
    text:
      blacklist: ["badword"]

# read full documentation of plugins here https://git.io/J3NuC

##########################

# make sure you understand the configuration before you run
# edit this file to suit your needs
# read more here https://github.com/aahnik/tgcf